- name: Adding APT repository key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: Adding APT repository
  apt_repository:
    repo: "deb https://deb.nodesource.com/iojs_{{iojs_version.split('.').0}}.x {{ansible_distribution_release}} main"
    update_cache: yes

- name: Installing io.js
  apt:
    name: "iojs={{iojs_version}}"
    state: present
